fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\Type\RegistrationType
    from_email:
        address: you@example.com
        sender_name: You
